name: Publish the package to Github Package Registry
on:
  release:
    types: [created]
permissions:
  packages: write
jobs:
  github-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2 
      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
      - name: Install dependencies and build with builder bob
        run: yarn install --frozen-lockfile 
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > /home/runner/work/_temp/.npmrc
      - run: echo "@pagopa:registry=https://npm.pkg.github.com/" >> /home/runner/work/_temp/.npmrc
      - run: echo "always-auth=true" >> /home/runner/work/_temp/.npmrc
      - name: Read .npmrc
        run: cat /home/runner/work/_temp/.npmrc
      - name: Publish Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
